### ISSUE TITLE
How to deal with MemoryError?

### ISSUE THREAD

**Issue by saberman888** [libertysoft3/reddit-html-archiver#4]
I'm archiving nearly 10 years worth of Reddit posts, and when I do so I get this MemoryError:
`Traceback (most recent call last):
  File "write_html.py", line 753, in <module>
    generate_html(args.min_score, args.min_comments, hide_deleted_comments)
  File "write_html.py", line 125, in generate_html
    write_link_page(subs, l, sub, hide_deleted_comments)
  File "write_html.py", line 277, in write_link_page
    comments_html += comment_html + '\n'
MemoryError`

I've tried to troubleshoot this by watching trough Task Manager and making sure it had enough RAM. Perhaps it's because I'm using python 32 bit, but the error occurs way before it reaches 2GB of Ram.

**Comment by libertysoft3** [comment]
I suspect you are running out of memory because you hit a post with a huge number of comments. I don't have any sort of comments per page limit.

I don't know how I could write this bit for efficiently. I think the easiest fix is for you to run write_html.py on a 64 bit machine. You can certainly copy the data folder over so that you don't have to re-download everything.

Maybe increasing your page file on Windows would help, but everyone is saying just use 64-bit. I think your available 2GB or 4GB of RAM is also shared with your OS, etc. You could also skip some comments for this one post, but that's no fun either.

**Comment by saberman888** [comment]
That did it and I should have used x64 bit python.

**Comment by libertysoft3** [comment]
yay
